# Generated by Django 5.2 on 2025-05-10 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SLIDER', 'Slider Scale'), ('BINARY', 'Binary Choice'), ('SHORT', 'Short Answer')], max_length=10)),
                ('system_prompt', models.TextField()),
                ('example_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_data', models.JSONField()),
                ('source_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_quiz.couple')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_quiz.quiztemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ChatKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_phrase', models.BooleanField(default=False)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_quiz.couple')),
            ],
            options={
                'unique_together': {('couple', 'keyword')},
            },
        ),
    ]
