# Generated by Django 5.2 on 2025-05-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Honeymoon', 'Dating/Honeymoon'), ('Exploration', 'Doubt & Denial/Exploration'), ('Adaptation', 'Disillusionment/Adaptation'), ('Commitment', 'Decision/Commitment'), ('Acceptance', 'True Love/Acceptance')], max_length=50)),
                ('open_communication', models.IntegerField()),
                ('trust', models.IntegerField()),
                ('individuality', models.IntegerField()),
                ('curiosity', models.IntegerField()),
                ('time_apart', models.IntegerField()),
                ('playfulness', models.IntegerField()),
                ('physical_intimacy', models.IntegerField()),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_quiz.couple')),
            ],
        ),
    ]
